[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.poetry]
name = "mypg"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

dependencies = [
    "pytest>=7.0.0"
]